spring:
  application:
    name: activity-service
  data:
    mongodb:
      uri: mongodb://admin:123@localhost:27017/fitnessdb?authSource=admin
      port: 27017
      database: fitnessdb
      username: admin
      password: 123

server:
  port: 8082

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/